### ISSUE TITLE
Clojure 1.9.0 - "WARNING: any? already refers to: #'clojure.core/any?"

### ISSUE THREAD

**Issue by mbjarland** [marick/suchwow#10]
I'm building a leiningen project with the latest (1.9.0) version of midje as a dependency, which in turn pulls in suchwow 6.0.0. Running `> lein midje` to execute the test suite produces the following warning: 

```
> lein midje
WARNING: any? already refers to: #'clojure.core/any? in namespace: com.rpl.specter.impl, being replaced by: #'com.rpl.specter.impl/any?
```

I have spoken with Nathan, the maintainer of specter and he has fixed this issue in a later version of specter. The relevant part of my dependency tree looks as follows: 

```
[midje "1.9.0" :scope "test"]
   [marick/suchwow "6.0.0" :scope "test" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
     [com.rpl/specter "0.13.0" :scope "test" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
```

i.e. in order to get midje to stop throwing warnings we would need to update the version of specter which in turn would require suchwow to update it's dependency to specter and releasing a new version followed by a update by midje. 

So we need to update the dependency to specter to a later version to eliminate warnings when running under clojure 1.9.0.

**Comment by mbjarland** [comment]
This issue is a duplicate of issue #9 which for some arcane reason does not seem to be visible by going to the issues page and listing issues. #9 has a pending pull request which fixes this issue. 

+1 for accepting that PR.

**Comment by marick** [comment]
Accepted. Someone want to bump the version and make a new release of suchwow? If not, I'll do it.
