### ISSUE TITLE
Upgrade specter which had breaking API changes

### ISSUE THREAD

**Issue by rauhs** [marick/suchwow#3]
I use the latest specter and midje (which pulls in suchwow). They don't play nice anymore. Can suchwow upgrade the dependency?

Would only need to change the two `specter/transform` calls:

https://github.com/marick/suchwow/blob/66623d6e16a12906197d5994bcfc7d637a355c03/src/such/readable.clj#L175

to `com.rpl.specter.macros/transform`.

**Comment by marick** [comment]
Working on this. It has revealed some dependency hell (flatland/ordered) that I don't understand.

**Comment by marick** [comment]
Fixed in 5.1.3 - and structural typing 2.0.3 - and Midje 1.9.0-alpha2
