### ISSUE TITLE
Considering upgrade of specter?

### ISSUE THREAD

**Issue by nlessa** [marick/suchwow#7]
Hi,
I am an user of Midje ( (1.9.0-alpha5) and Specter and suchwow at the current version is blocking use of Specter last version (probably because the change in the macros namespaces).
Are considering upgrading suchwow to 0.13.0 of specter? And after, upgrading midje?

Bests.

**Comment by marick** [comment]
I will do that after two pressing deadlines, the second of which is on the 17th.

**Comment by marick** [comment]
I'm having trouble upgrading Specter to 0.13, given the way I used the 0.11 version. If you know Specter well, perhaps you can help out with this? https://github.com/nathanmarz/specter/issues/154

**Comment by marick** [comment]
Regardless of that (which it turns out doesn't affect Midje), this is fixed and Midje has also been upgraded (1.9.0-alpha6)
