### ISSUE TITLE
Not conforming spec (in clojure-1.9.0-alpha13)

### ISSUE THREAD

**Issue by nlessa** [marick/suchwow#8]
Hi,
Trying to upgrade my project to clojure-1.9.0-alpha and got this error 
Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/ns did not conform to spec:
In: [1] val: ((require [such.wrongness :as !])) fails at: [:args] predicate: (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses),  Extra input
:clojure.spec/args  (such.sequences (require [such.wrongness :as !]))

It seems that "!" is not being accept by clojure/spec as valid. (it's my guess).

Do you intend to upgrade suchwow (and midje) to these pre-releases clojure 1.9?

**Comment by marick** [comment]
I'm behind in my commitments so I can't/won't check, but: are you using the most recent Midje (alpha-6)? I fixed a similar "bug" recently. (The issue is that the new clojure rejects formerly-valid namespace declarations.)

**Comment by marick** [comment]
Both suchwow (6.0.0) and Midje (1.9-alpha6) are now compatible with Clojure 1.9-alpha13.
